using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SiXiangFakeData : MonoBehaviour
{
    // Start is called before the first frame update
    public static SiXiangFakeData Instance;
    [HideInInspector] public string getFreespin = "";
    [HideInInspector] public string scatterSpin = "{\"reward\":0,\"winAmount\":0,\"userAmount\":389417,\"numberOfDragonPearlSpins\":3,\"dragonPearls\":[{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.4,\"winAmount\":4000,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.337,\"winAmount\":3370,\"jackpot\":0,\"row\":2,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":6,\"luckyMoney\":0,\"multiplier\":2.684,\"winAmount\":26840,\"jackpot\":0,\"row\":0,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.044,\"winAmount\":439,\"jackpot\":0,\"row\":0,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.044999998,\"winAmount\":449,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":5,\"luckyMoney\":0,\"multiplier\":1.044,\"winAmount\":10440,\"jackpot\":0,\"row\":1,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false}],\"dragonPearlWinPot\":45539,\"numberOfGoldPicks\":0}";
    [HideInInspector] public string getInfoDragonPearl = "{\"minor\":10,\"major\":20,\"mega\":30,\"grand\":150,\"payTable\":[[0.0,0.0,0.5,2.5,5.0],[0.0,0.0,0.5,2.5,5.0],[0.0,0.0,0.5,2.5,5.0],[0.0,0.0,0.5,2.5,5.0],[0.0,0.0,0.5,2.5,5.0],[0.0,0.0,2.0,10.0,20.0],[0.0,0.0,1.5,7.5,15.0],[0.0,0.0,1.2,6.0,12.0],[0.0,0.0,1.0,5.0,10.0],[0.0,0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0,0.0]],\"betLevels\":[1,5,50,500,1000,2500,5000,10000,25000,50000,100000],\"bet\":500,\"userAmount\":2686425,\"gameType\":2,\"isBonusGame\":false,\"bonusGameMultiplier\":4.0,\"winAmount\":4347,\"pearls\":[{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.966,\"winAmount\":483,\"jackpot\":0,\"row\":0,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.208,\"winAmount\":104,\"jackpot\":0,\"row\":0,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":1,\"luckyMoney\":1,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.07,\"winAmount\":35,\"jackpot\":0,\"row\":0,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.97400004,\"winAmount\":487,\"jackpot\":0,\"row\":0,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":6,\"luckyMoney\":0,\"multiplier\":5.36,\"winAmount\":2680,\"jackpot\":0,\"row\":1,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.362,\"winAmount\":180,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":1,\"luckyMoney\":2,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":1,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.118,\"winAmount\":59,\"jackpot\":0,\"row\":2,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.077999994,\"winAmount\":38,\"jackpot\":0,\"row\":2,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":1,\"luckyMoney\":3,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":2,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.478,\"winAmount\":238,\"jackpot\":0,\"row\":2,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.082,\"winAmount\":41,\"jackpot\":0,\"row\":2,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false}],\"numberOfDragonPearlSpins\":5,\"numberOfPick\":0,\"cards\":[],\"rewards\":[]}";

    [HideInInspector] private string getBuyBonusDragonPearl = "{\"userAmount\":411187,\"multiplier\":90,\"price\":90,\"miniGameType\":2,\"bet\":1,\"numberOfDragonPearlSpins\":3,\"dragonPearls\":[{\"item\":6,\"luckyMoney\":0,\"multiplier\":2.695,\"winAmount\":2,\"jackpot\":0,\"row\":1,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.044,\"winAmount\":0,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.046,\"winAmount\":0,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":5,\"luckyMoney\":0,\"multiplier\":1.5580001,\"winAmount\":1,\"jackpot\":0,\"row\":1,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":5,\"luckyMoney\":0,\"multiplier\":1.5580001,\"winAmount\":1,\"jackpot\":0,\"row\":2,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.30400002,\"winAmount\":0,\"jackpot\":0,\"row\":0,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false}],\"dragonPearlWinPot\":6,\"numberOfGoldPicks\":0}";
    [HideInInspector] public string getBachHoDragonPearl = "{\"pearls\":[{\"item\":1,\"luckyMoney\":2,\"multiplier\":0,\"winAmount\":0,\"jackpot\":0,\"row\":2,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":1.074,\"winAmount\":53,\"jackpot\":0,\"row\":0,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.106,\"winAmount\":5,\"jackpot\":0,\"row\":0,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":6,\"luckyMoney\":0,\"multiplier\":5.87,\"winAmount\":293,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.414,\"winAmount\":20,\"jackpot\":0,\"row\":1,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":5,\"luckyMoney\":0,\"multiplier\":3.254,\"winAmount\":162,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.063999996,\"winAmount\":3,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.34,\"winAmount\":17,\"jackpot\":0,\"row\":1,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.39200002,\"winAmount\":19,\"jackpot\":0,\"row\":2,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.702,\"winAmount\":35,\"jackpot\":0,\"row\":2,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.062,\"winAmount\":3,\"jackpot\":0,\"row\":2,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true}],\"numberOfBonusSpins\":1,\"totalSpins\":3,\"isGrandJackpot\":false,\"isFinished\":false,\"winAmount\":1113,\"userAmount\":347206,\"isSelectBonusGame\":false}";
    [HideInInspector] public string getChuTuocDP = "{\"pearls\":[{\"item\":1,\"luckyMoney\":3,\"multiplier\":0,\"winAmount\":0,\"jackpot\":0,\"row\":1,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":6,\"luckyMoney\":0,\"multiplier\":2.579,\"winAmount\":128,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":5,\"luckyMoney\":0,\"multiplier\":1.767,\"winAmount\":88,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false}],\"numberOfBonusSpins\":1,\"totalSpins\":2,\"isGrandJackpot\":true,\"isFinished\":true,\"winAmount\":8495,\"userAmount\":346556,\"isSelectBonusGame\":false}";
    [HideInInspector] public string HuyenVuDragonPearl = "{\"pearls\":[{\"item\":1,\"luckyMoney\":1,\"multiplier\":0,\"winAmount\":0,\"jackpot\":0,\"row\":2,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false}],\"numberOfBonusSpins\":4,\"totalSpins\":4,\"isGrandJackpot\":false,\"isFinished\":false,\"winAmount\":196,\"userAmount\":344349,\"isSelectBonusGame\":false}";
    [HideInInspector] private string NormalSpinGetScatter = "{\"winAmount\":50000,\"userAmount\":105339479,\"isGrandJackpot\":false,\"isBonusMiniGame\":true,\"payLines\":[{\"winAmount\":50000,\"line\":[3,7,3,2,6],\"lineNumber\":4,\"symbol\":3,\"numberOfSymbols\":3},{\"winAmount\":50000,\"line\":[3,9,3,4,6],\"lineNumber\":18,\"symbol\":3,\"numberOfSymbols\":3},{\"winAmount\":50000,\"line\":[3,0,3,1,6],\"lineNumber\":20,\"symbol\":3,\"numberOfSymbols\":3}],\"reels\":[[10,2,3],[10,7,9],[3,1,4],[1,2,4],[10,2,6]],\"isSelectBonusGame\":false}";
    [HideInInspector] private string DragonPearlFinishedSpin = "{\"pearls\":[{\"item\":1,\"luckyMoney\":1,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":1,\"luckyMoney\":3,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":2,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.038999997,\"winAmount\":19,\"jackpot\":0,\"row\":2,\"col\":1,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.181,\"winAmount\":90,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.239,\"winAmount\":119,\"jackpot\":0,\"row\":2,\"col\":3,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false}],\"numberOfBonusSpins\":4,\"totalSpins\":6,\"isGrandJackpot\":false,\"isFinished\":false,\"winAmount\":2173,\"userAmount\":2686425,\"isSelectBonusGame\":false}";
    [HideInInspector] private string ScatterSpin = "{\"reward\":0,\"winAmount\":0,\"userAmount\":305849,\"numberOfDragonPearlSpins\":3,\"dragonPearls\":[{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.051,\"winAmount\":509,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.052,\"winAmount\":520,\"jackpot\":0,\"row\":2,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.243,\"winAmount\":2430,\"jackpot\":0,\"row\":0,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.337,\"winAmount\":3370,\"jackpot\":0,\"row\":2,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.139,\"winAmount\":1389,\"jackpot\":0,\"row\":1,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.523,\"winAmount\":5230,\"jackpot\":0,\"row\":1,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false}],\"dragonPearlWinPot\":13450,\"numberOfGoldPicks\":0}";
    [HideInInspector] public string GrandJackpotNormalSpin = "{\"winAmount\":74500,\"userAmount\":2146689,\"isGrandJackpot\":true,\"isBonusMiniGame\":false,\"payLines\":[],\"reels\":[[9,4,1],[1,9,8],[6,2,9],[9,1,9],[4,8,9]],\"isSelectBonusGame\":false}";
    [HideInInspector] public string DragonPearlSpinBug1 = "{\"pearls\":[{\"item\":1,\"luckyMoney\":3,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":2,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.035,\"winAmount\":17,\"jackpot\":0,\"row\":0,\"col\":1,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.185,\"winAmount\":92,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.105000004,\"winAmount\":52,\"jackpot\":0,\"row\":0,\"col\":4,\"isBonusSpin\":true,\"isJackpot\":false,\"isDoubled\":false},{\"item\":1,\"luckyMoney\":2,\"multiplier\":0.0,\"winAmount\":0,\"jackpot\":0,\"row\":1,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":false},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.085999995,\"winAmount\":42,\"jackpot\":0,\"row\":0,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.07,\"winAmount\":35,\"jackpot\":0,\"row\":0,\"col\":1,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.37,\"winAmount\":185,\"jackpot\":0,\"row\":0,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":2,\"luckyMoney\":0,\"multiplier\":0.088,\"winAmount\":43,\"jackpot\":0,\"row\":0,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.21000001,\"winAmount\":105,\"jackpot\":0,\"row\":0,\"col\":4,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":5,\"luckyMoney\":0,\"multiplier\":3.7,\"winAmount\":1850,\"jackpot\":0,\"row\":1,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":3,\"luckyMoney\":0,\"multiplier\":0.228,\"winAmount\":114,\"jackpot\":0,\"row\":1,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":4,\"luckyMoney\":0,\"multiplier\":0.93000007,\"winAmount\":465,\"jackpot\":0,\"row\":2,\"col\":0,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":6,\"luckyMoney\":0,\"multiplier\":5.554,\"winAmount\":2776,\"jackpot\":0,\"row\":2,\"col\":2,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true},{\"item\":5,\"luckyMoney\":0,\"multiplier\":3.2680001,\"winAmount\":1634,\"jackpot\":0,\"row\":2,\"col\":3,\"isBonusSpin\":false,\"isJackpot\":false,\"isDoubled\":true}],\"numberOfBonusSpins\":1,\"totalSpins\":3,\"isGrandJackpot\":false,\"isFinished\":false,\"winAmount\":7251,\"userAmount\":1206312,\"isSelectBonusGame\":false}";
    [HideInInspector] private string BugSpin1 = "{\"winAmount\":-1000,\"userAmount\":904491,\"isGrandJackpot\":false,\"isBonusMiniGame\":false,\"payLines\":[{\"winAmount\":1000,\"line\":[1,1,1,6,10],\"lineNumber\":16,\"symbol\":1,\"numberOfSymbols\":3}],\"reels\":[[6,1,0],[3,1,4],[0,6,1],[8,6,1],[4,10,3]],\"isSelectBonusGame\":false}";
    [HideInInspector] public string megaWinNormal = "{\"winAmount\":1860,\"userAmount\":256326,\"isGrandJackpot\":false,\"isBonusMiniGame\":false,\"payLines\":[{\"winAmount\":50,\"line\":[0,9,2,3,4],\"lineNumber\":0,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[9,7,2,3,3],\"lineNumber\":1,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[7,3,7,9,8],\"lineNumber\":2,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[9,9,7,3,3],\"lineNumber\":3,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[7,9,2,3,8],\"lineNumber\":4,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[0,7,2,3,4],\"lineNumber\":5,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[0,3,7,9,4],\"lineNumber\":6,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[9,7,2,9,8],\"lineNumber\":7,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[7,3,2,3,3],\"lineNumber\":8,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[0,3,2,3,4],\"lineNumber\":9,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[0,7,2,9,4],\"lineNumber\":10,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[9,9,2,3,3],\"lineNumber\":11,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[7,9,2,3,8],\"lineNumber\":12,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[9,9,2,3,3],\"lineNumber\":13,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[7,9,7,3,8],\"lineNumber\":14,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[0,9,2,3,4],\"lineNumber\":15,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[0,9,7,3,4],\"lineNumber\":16,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[9,7,7,3,3],\"lineNumber\":17,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[7,3,2,9,8],\"lineNumber\":18,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[9,3,7,9,3],\"lineNumber\":19,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[7,7,2,3,8],\"lineNumber\":20,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[0,3,2,9,4],\"lineNumber\":21,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[0,7,7,3,4],\"lineNumber\":22,\"symbol\":7,\"numberOfSymbols\":4},{\"winAmount\":50,\"line\":[9,3,2,9,3],\"lineNumber\":23,\"symbol\":2,\"numberOfSymbols\":4},{\"winAmount\":120,\"line\":[7,7,7,3,8],\"lineNumber\":24,\"symbol\":7,\"numberOfSymbols\":4}],\"reels\":[[9,0,7],[7,9,3],[2,2,7],[3,3,9],[3,4,8]],\"isSelectBonusGame\":false}";
    [HideInInspector] private string bugSpinScatter = "{\"winAmount\":-1000,\"userAmount\":903491,\"isGrandJackpot\":false,\"isBonusMiniGame\":true,\"payLines\":[{\"winAmount\":1000,\"line\":[4,4,4,5,3],\"lineNumber\":24,\"symbol\":4,\"numberOfSymbols\":3}],\"reels\":[[10,2,4],[4,2,3],[10,3,4],[5,3,8],[10,2,3]],\"isSelectBonusGame\":false}";
    [HideInInspector] public string bugSpin = "{\"winAmount\":62000,\"userAmount\":2428592,\"isGrandJackpot\":false,\"isBonusMiniGame\":true,\"payLines\":[{\"winAmount\":12000,\"line\":[9,7,7,8,0],\"lineNumber\":2,\"symbol\":7,\"numberOfSymbols\":3},{\"winAmount\":12000,\"line\":[10,7,7,2,10],\"lineNumber\":3,\"symbol\":7,\"numberOfSymbols\":3},{\"winAmount\":12000,\"line\":[2,7,7,8,4],\"lineNumber\":6,\"symbol\":7,\"numberOfSymbols\":3},{\"winAmount\":12000,\"line\":[9,7,7,2,0],\"lineNumber\":14,\"symbol\":7,\"numberOfSymbols\":3},{\"winAmount\":12000,\"line\":[2,7,7,2,4],\"lineNumber\":16,\"symbol\":7,\"numberOfSymbols\":3},{\"winAmount\":12000,\"line\":[10,7,7,8,10],\"lineNumber\":19,\"symbol\":7,\"numberOfSymbols\":3}],\"reels\":[[10,2,9],[2,7,7],[10,1,7],[4,2,8],[10,4,0]],\"isSelectBonusGame\":false}";
    void Start()
    {
        Instance = this;
    }
    public string getHuyenVuDragonPearl()
    {
        return HuyenVuDragonPearl;
    }
    public string getBugSpin()
    {
        return BugSpin1;
    }
    public string getDragonPearlFinishedSpin()
    {
        return DragonPearlFinishedSpin;
    }
    public string getScatterSpin()
    {
        return ScatterSpin;
    }
    public string getNormalScatter()
    {
        return NormalSpinGetScatter;
    }
    // Update is called once per frame
    void Update()
    {

    }
}
